### ISSUE TITLE
Downloading multiple files results into MemoryError

### ISSUE THREAD

**Issue by tanishqjasoria** [gsuitedevs/PyDrive#202]
PyDrive keep files in the memory even after the file is saved on the disk.

**Comment by shcheklein** [comment]
@tanishqjasoria this (and many other) issue is fixed in the [iterative/PyDrive2](https://github.com/iterative/PyDrive2) - a maintained fork. `GetContentFile` does not store content in memory at all now (so it can handle large files as well).

Here is an example on how it is used in [DVC](https://dvc.org) - https://github.com/iterative/dvc/blob/b57077af11ae287941b4d2939071fda2ad01f483/dvc/remote/gdrive.py#L376

**Comment by tanishqjasoria** [comment]
Okay. Thanks for the info!
